import tkinter as tk
from tkinter import filedialog, messagebox

def generate_gcode():
    try:
        x = float(entry_x.get())
        y = float(entry_y.get())
        tool_d = float(entry_tool.get())
        depth = float(entry_depth.get())
        step = float(entry_step.get())
        feed = float(entry_feed.get())

        offset = tool_d / 2
        gcode = [
            "(Generated by Happy Cutter v1.1)",
            "G21 ; Метрическая система",
            "G90 ; Абсолютные координаты",
            "M3 S10000 ; Шпиндель ВКЛ",
            "G0 Z5 ; Безопасная высота"
        ]

        curr_z = 0
        while curr_z > -depth:
            curr_z -= step
            if curr_z < -depth: curr_z = -depth
            
            gcode.append(f"G1 Z{curr_z:.3f} F100")
            gcode.append(f"G1 X{x + offset:.3f} Y{-offset:.3f} F{feed}")
            gcode.append(f"G1 X{x + offset:.3f} Y{y + offset:.3f}")
            gcode.append(f"G1 X{-offset:.3f} Y{y + offset:.3f}")
            gcode.append(f"G1 X{-offset:.3f} Y{-offset:.3f}")

        gcode.append("G0 Z5")
        gcode.append("M5\nM30")

        full_code = "\n".join(gcode)
        text_preview.delete(1.0, tk.END)
        text_preview.insert(tk.END, full_code)
        return full_code
        
    except ValueError:
        messagebox.showerror("Ошибка", "Введите корректные числа!")
        return None

def save_file():
    code = generate_gcode()
    if code:
        file_path = filedialog.asksaveasfilename(defaultextension=".nc", filetypes=[("G-Code", "*.nc"), ("All files", "*.*")])
        if file_path:
            with open(file_path, "w") as f:
                f.write(code)
            messagebox.showinfo("Успех", "Файл для станка сохранен!")

root = tk.Tk()
root.title("Happy Cutter v1.1")

# Сетка интерфейса
fields = [
    ("Ширина X (мм):", "50"),
    ("Высота Y (мм):", "50"),
    ("Фреза D (мм):", "2.0"),
    ("Глубина (мм):", "1.6"),
    ("Шаг Z (мм):", "0.5"),
    ("Подача (F):", "500")
]

entries = {}
for i, (label_text, default) in enumerate(fields):
    tk.Label(root, text=label_text).grid(row=i, column=0, sticky="e", padx=5, pady=2)
    en = tk.Entry(root)
    en.insert(0, default)
    en.grid(row=i, column=1, padx=5, pady=2)
    entries[label_text] = en

# Привязываем переменные для удобства (костыль для простоты)
entry_x, entry_y, entry_tool, entry_depth, entry_step, entry_feed = [entries[f[0]] for f in fields]

tk.Button(root, text="1. Предпросмотр", command=generate_gcode).grid(row=len(fields), column=0, pady=10)
tk.Button(root, text="2. Сохранить .nc", command=save_file).grid(row=len(fields), column=1, pady=10)

text_preview = tk.Text(root, height=10, width=45)
text_preview.grid(row=len(fields)+1, column=0, columnspan=2, padx=10, pady=10)

root.mainloop()

